# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cbc5c60c6c9b8a693712e9577ba369ad"
name = "xpertapp"
handle = "xpertapp"
application_url = "https://missouri-victorian-premiere-close.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "products/create" ]
  uri = "/webhooks/products/create"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/products/update"

  [[webhooks.subscriptions]]
  topics = [ "products/delete" ]
  uri = "/webhooks/products/delete"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_product_listings"

[auth]
redirect_urls = [
  "https://missouri-victorian-premiere-close.trycloudflare.com/auth/callback",
  "https://missouri-victorian-premiere-close.trycloudflare.com/auth/shopify/callback",
  "https://missouri-victorian-premiere-close.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://missouri-victorian-premiere-close.trycloudflare.com"
subpath = "xpertsearch"
prefix = "apps"

[pos]
embedded = false

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
